- README.md
- src/scripts/home.ts
> fix: Memubar click error

- vite.config.ts
Add @connect to your script to automatically allow cross-origin requests
> feat: auto allow cors request

- package.json
- pnpm-lock.yaml
- src/main.ts
- src/pages/player.ts
- src/player/index.ts
- src/player/plugins/panelInfo/javInfoRenderer.ts
- src/player/plugins/panelInfo/panelInfo.ts
- src/player/plugins/thumbnails/thumbnails.ts
- src/types/global.d.ts
- src/utils/version-output.ts
- vite.config.ts
- Move type dependencies to devDependencies
- Update Vite configuration with more detailed userscript metadata
- Implement dynamic module loading for Hls.js
- Modify main entry point to support different document ready states
- Add global type declaration for Hls
- Simplify version output utility
- Improve player interaction with single and double-click handling
- Update preview image rendering and plugin registration
> refactor: Enhance project configuration and module loading

- src/components/FileOperationMenu/index.ts
- src/components/FileOperationMenu/styles.css
- src/pages/home.ts
- src/styles/tooltip.css
- vite.config.ts
> feat: Added playback support for thumbnails and search file lists

- src/pages/video/index.vue
- src/utils/drive115/core.ts
- src/utils/drive115/docs/vod域名跨域授权流程既复现播放列表失败.md
> fix: login timeout

- src/components/XPlayer/components/Controls/index.vue
- src/components/XPlayer/components/Menu/index.vue
- src/components/XPlayer/hooks/useControls.ts
- src/components/XPlayer/index.vue
> fix: The XPlayer control bar should not be automatically hidden in the control bar

- src/components/XPlayer/components/Controls/index.vue
- src/components/XPlayer/hooks/useControls.ts
- src/components/XPlayer/index.vue
> fix: Missing immersive progress bar

- src/components/XPlayer/components/Controls/QualityButton.vue
- src/components/XPlayer/components/Controls/SubtitleButton.vue
- src/components/XPlayer/hooks/usePlayer.ts
- src/components/XPlayer/hooks/useSubtitles.ts
- src/components/XPlayer/index.vue
- src/pages/video/data/useSubtitlesData.ts
- src/pages/video/index.vue
> fix: Subtitle loading error

- package.json
- pnpm-lock.yaml
- src/pages/video/index.ts
- vite.config.ts
> fix: meterial-icon-network-error

- src/pages/video/components/FileInfo/index.vue
- src/pages/video/components/Playlist/index.vue
- src/pages/video/data/useDataFileInfo.ts
- src/pages/video/data/useDataPlaylist.ts
- src/pages/video/index.vue
- src/utils/drive115/core.ts
- src/utils/jav/javDB.ts
- src/utils/request/gmRequst.ts
- src/utils/request/types.ts
- Change GMRequest's redirect to "manual" to allow concurrent requests
- JavDB requests responseType to be changed to "document" to avoid multiple redirections
> feat: Optimize the concurrency of oil monkey requests

- src/pages/home/FileListMod/index.ts
- src/pages/home/PageTitleMod/index.ts
- src/pages/home/index.ts
- src/utils/actressFaceDB.ts
- Support opening new tabs of folders with the middle mouse button
- Support displaying the current directory in Tab Title
> feat: Improve file list browsing

- src/components/XPlayer/hooks/usePlaybackRate.ts
- src/components/XPlayer/hooks/usePlaying.ts
- src/components/XPlayer/hooks/usePreferences.ts
- src/components/XPlayer/hooks/useVolume.ts
- src/components/XPlayer/index.vue
- Supports mute, volume, and playback speed preferences
> feat: Add player preferences

- src/components/XPlayer/hooks/usePlayer.ts
- src/components/XPlayer/hooks/useProgress.ts
- src/components/XPlayer/hooks/useSources.ts
- src/components/XPlayer/index.vue
- src/components/XPlayer/types/index.ts
- src/pages/video/data/useDataHistory.ts
- src/pages/video/data/useThumbnails.ts
- src/pages/video/data/useVideoSource.ts
- src/pages/video/index.vue
- src/utils/clipper/core.ts
- src/utils/clipper/m3u8.ts
- src/utils/drive115/api/vodApi/req.ts
- src/utils/drive115/api/vodApi/res.ts
- src/utils/drive115/core.ts
- src/utils/request/gmRequst.ts
- src/utils/request/types.ts
- src/utils/scheduler.ts
- Introduced history management for video playback tracking.
- Improved video source handling with error management during playback.
Closed #107
> feat: Enhance video player functionality with progress tracking and history management

- src/pages/video/index.ts
- Video Page changed to asynchronous loading
> fix: scrollbar lost

- src/components/XPlayer/components/Controls/PipButton.vue
- src/components/XPlayer/components/Controls/index.vue
- src/components/XPlayer/hooks/usePictureInPicture.ts
- src/components/XPlayer/hooks/usePlayerProvide.ts
- 在 XPlayer 控件中引入画中画按钮。
- 新增 usePictureInPicture 钩子以管理画中画状态和切换逻辑。
- 更新 usePlayerProvide 以支持画中画功能。
Close #57
> feat: 添加画中画功能

- src/components/XPlayer/components/Controls/TimeDisplay.vue
- src/components/XPlayer/components/Controls/VolumeControl.vue
- src/components/XPlayer/components/HUD/index.ts
- src/components/XPlayer/components/HUD/index.vue
- src/components/XPlayer/components/Popup/index.vue
- src/components/XPlayer/hooks/useHotKey.ts
- src/components/XPlayer/hooks/useHud.ts
- src/components/XPlayer/hooks/usePlaybackRate.ts
- src/components/XPlayer/hooks/usePlayerProvide.ts
- src/components/XPlayer/index.vue
- src/components/XPlayer/types/hud.ts
- Added HUD component to display contextual messages for volume, playback speed, and transformations.
- Updated hotkey functionality to include HUD notifications for fast forward and rewind actions.
- Refactored Popup component to support locking controls during HUD display.
> feat: Implement HUD for player notifications

- src/utils/clipper/core.ts
- Improve performance by approximately 60%
- Added initial and step chunk size options to ClipperOptions for better control over data fetching.
- Implemented fetchBufferRange method to retrieve specific byte ranges from a URL.
- Refactored createDecodePipeline and processStreamingSegment methods to improve streaming and decoding of MP4 video segments.
- Introduced error handling and retry logic for robust video processing.
- Updated type definitions for MP4 video tracks and file information.
> feat: Enhance ClipperCore with MP4 processing capabilities

- src/components/XPlayer/hooks/playerCore/types.ts
- src/components/XPlayer/hooks/playerCore/useAvPlayerCore.ts
- src/components/XPlayer/hooks/playerCore/useNativePlayerCore.ts
- src/components/XPlayer/hooks/playerCore/usePlayerCore.ts
- src/components/XPlayer/hooks/playerCore/usePlayerCoreState.ts
- src/components/XPlayer/hooks/useTransform.ts
> fix: scaling error after player rotation

- src/components/XPlayer/components/Controls/ControlBar.vue
- src/components/XPlayer/components/Controls/SettingsButton.vue
- src/components/XPlayer/components/Controls/ThumbnailSettings.vue
- src/components/XPlayer/components/Controls/TransformSettings.vue
- src/components/XPlayer/components/Controls/VideoEnhanceSettings.vue
- src/components/XPlayer/hooks/useVideoEnhance.ts
- src/components/XPlayer/utils/icon.ts
- Optimize video player control bar interface
- Refactor video enhancement settings component with more adjustment options
- Improve video enhancement functionality implementation and user experience
- Update player settings button and thumbnail settings
- Enhance transform settings functionality
- Add new icon support
Major changes:
- Significantly optimized useVideoEnhance hook implementation
- Enhanced VideoEnhanceSettings component functionality
Close #194
> feat: enhance video player controls and video enhancement features

- src/components/XPlayer/components/Loading/index.vue
> fix: Loading style error in the player

- src/components/XPlayer/components/Controls/PlaySettings.vue
- src/components/XPlayer/components/Controls/SettingsButton.vue
- src/components/XPlayer/components/Controls/VolumeControl.vue
- src/components/XPlayer/hooks/playerCore/types.ts
- src/components/XPlayer/hooks/playerCore/useAvPlayerCore.ts
- src/components/XPlayer/hooks/playerCore/useNativePlayerCore.ts
- src/components/XPlayer/hooks/playerCore/usePlayerCore.ts
- src/components/XPlayer/hooks/playerCore/usePlayerCoreState.ts
- src/components/XPlayer/hooks/useHotKey.ts
- src/components/XPlayer/hooks/useHud.ts
- src/components/XPlayer/hooks/usePlaySettings.ts
- src/components/XPlayer/hooks/usePlayerProvide.ts
- src/components/XPlayer/hooks/useSources.ts
- src/components/XPlayer/types/index.ts
- src/components/XPlayer/utils/icon.ts
- src/pages/video/data/usePreferences.ts
- src/pages/video/index.vue
- Added Playback Settings component to Settings button
- Optimize volume control logic and add audio recovery tips.
- Updated player core status, support audio recovery function.
- Add auto play option to improve user experience.
close #198
> feat: Optimizing Audio Hanging and Autoplay Strategies

- src/hooks/usePreview/index.ts
- src/pages/home/FileListMod/FileItemLoader.ts
- src/pages/home/FileListMod/extInfo.ts
- src/pages/home/FileListMod/index.css
- src/pages/home/FileListMod/index.ts
- src/pages/home/FileListMod/preview.ts
- src/pages/home/components/ExtPreview/index.vue
- src/pages/home/types.ts
- src/pages/video/components/Playlist/index.vue
- src/pages/video/components/Playlist/item.vue
- src/pages/video/data/useThumbnails.ts
- src/utils/cache/core/const.ts
- src/utils/cache/previewCache.ts
- src/utils/scheduler.ts
- Optimize the logic of getting and displaying preview images.
- Add preview image scheduler to support concurrent task management.
- Update the data structure of preview map to support more options and error handling.
- Optimize file list and playlist components to enhance user experience.
close #213
> feat: Updated preview image functionality and scheduler

- src/pages/video/components/HeaderInfo/index.vue
- src/pages/video/components/Playlist/index.vue
- src/pages/video/data/useDataPlaylist.ts
- src/pages/video/index.vue
- src/utils/drive115/wrap.ts
> feat: Add file path display and jump

- src/pages/video/data/useSubtitlesData.ts
- src/pages/video/index.vue
- src/utils/array.ts
- src/utils/string.ts
> feat: Enhance subtitle handling, add file name similarity sorting

- src/pages/video/data/usePreferences.ts
- Disable listening for storage changes in preferences
> feat: Optimize player preferences

- src/pages/home/BaseMod/index.ts
- src/pages/home/FileListMod/index.ts
- src/pages/home/TopFilePathMod/index.ts
- src/pages/home/TopHeaderMod/index.ts
- src/pages/home/index.ts
- Integrate each module (FileListMod, TopFilePathMod, TopHeaderMod) into ModManager to simplify initialization and destruction logic.
- Make FileListMod, TopFilePathMod, TopHeaderMod inherit from BaseMod to enhance code reusability.
> refactor: Refactoring homepage module management
